name: Pull request workflow

on:
  pull_request:
    types: [opened, reopened]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Run linting tests
      run: | 
        flake8 src/model/
    - name: Install pytest
      run: |
        python -m pip install pytest
    - name: Run unit tests
      run: |
        python tests/test_train.py



