name: Pull request workflow

on:
  pull_request:
    types: [opened, reopened]

jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Run linting tests
      run: | 
        flake8 src/model/
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python -m pip -r requirements.txt
    - name: Run unit tests
      run: |
        python tests/



