name: Trigger an Azure Machine Learning job when changes being pushed to the main branch

on:
  push:
    branches:
      - 'main'

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Submit training run
      run: |
        az ml job create --resource-group e2e-ml-ops --workspace e2e-ml-ops-ws --file src/job.yml --set inputs.training_data.path="azureml:diabetes-dev-folder@latest"
  production:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Submit training run
      run: |
        az ml job create --resource-group e2e-ml-ops --workspace e2e-ml-ops-ws --file src/job.yml --set inputs.training_data.path="azureml:diabetes-prod-folder@latest"
